---
- name: Setting up
  hosts: all
  gather_facts: true
  roles:
    - { role: geerlingguy.pip, become: true }
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: Create dir for postgres cert
      ansible.builtin.apt.file:
        path: ~/.postgresql
        state: directory
    
    - name: Download postgres cert
      ansible.builtin.apt.command: bash -c 'wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O ~/.postgresql/root.crt'

    - name: Chmod postgres root.cert
      ansible.builtin.apt.file:
        path: ~/.postgresql/root.crt
        state: touch
        mode: 0600

- name: Deploy webservers
  hosts: all
  tasks:
    - name: Run redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        published_ports: "{{ app_port }}:3000"
        restart_policy: always
        restart: true
        container_default_behavior: no_defaults
        pull: true
        state: started
        env:
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_PORT: "{{ redmine_db_port | int }}"

- name: Setting up datadog agent
  hosts: webservers
  roles:
    - role: datadog.datadog
      become: true
