---
- name: Setting up
  hosts: all
  gather_facts: true
  roles:
    - { role: geerlingguy.pip, become: true }
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Check that the somefile.conf exists
      ansible.builtin.stat:
        path: ~/.postgresql/root.crt
      register: postgres_cert

    - name: Create dir for postgres cert
      ansible.builtin.file:
        path: ~/.postgresql
        state: directory

    - name: Download postgres cert
      ansible.builtin.command: bash -c 'wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O ~/.postgresql/root.crt'
      when: not postgres_cert.stat.exists

- name: Deploy webservers
  hosts: all
  tasks:
    - name: Prepare .env file
      ansible.builtin.template:
        src: templates/.env.j2
        dest: ~/.env

    - name: Run redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        published_ports: "{{ app_port }}:3000"
        restart_policy: always
        restart: true
        container_default_behavior: no_defaults
        pull: true
        state: started
        env_file: ~/.env

- name: Setting up datadog agent
  hosts: webservers
  roles:
    - role: datadog.datadog
      become: true
